### ISSUE TITLE
Update MinIO example

### ISSUE THREAD

**Issue by mauricesnip** [qlico/qlico#19]
MinIO has [updated their Docker Quick Start Guide](https://github.com/minio/minio/issues/12660) to support the newest version of MinIO. The example given in the Qlico documentation results in the following warning (where 43503 is a random port):
```
WARNING: Console endpoint is listening on a dynamic port (43503), please use --console-address ":PORT" to choose a static port.
```
Result: unable to connect to http://minio.qlico:9000. This can be fixed by adding both ports and a `--console-address` flag to your docker-compose.yaml like so:
```yaml
minio:
  image: minio/minio
  container_name: qlico-core_minio
  ports:
    - 9000:9000
    - 9001:9001
  command: server /export --console-address :9001
  environment:
    MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:-qlicorocks}
    MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:-qlicorocks}
  volumes:
    - minio-data:/export
  networks:
    - qlico-core
  labels:
    - "traefik.http.routers.minio.rule=Host(`minio.qlico`)"
    - "traefik.http.services.minio.loadbalancer.server.port=9000"
```
